# Site settings
title: The Modern Concept Shop
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  The Modern Concept Shop is a cutting-edge marketing agency providing innovative solutions.
baseurl: "/ModernConceptShop" # the subpath of your site, e.g. /blog
url: "https://JavierArronis.github.io" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude unnecessary files and folders from the site build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor