# Site settings
title: The Modern Concept Shop
email: laura@themodernconcept.shop
description: >- # this means to ignore newlines until "baseurl:"
  The Modern Concept Shop helps B2B companies learn how to treat people like human beings rather than line items on a lead spreadsheet.
baseurl: "" # the subpath of your site, empty for the root
url: "https://themodernconcept.shop" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude unnecessary files and folders from the site build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  
  
